### ISSUE TITLE
ESX Error

### ISSUE THREAD

**Issue by AbrahamMoody** [KoZeuh/kMegaphone#1]
![kozeuh](https://user-images.githubusercontent.com/52460339/97648818-0054d000-1a56-11eb-85de-bfe88226309b.png)

Errorline:

RegisterNetEvent('esx:playerLoaded')
AddEventHandler('esx:playerLoaded', function(xPlayer)
    ESX.PlayerData = xPlayer
end)

Start Order:
start InteractSoundS
start RageUI
start kozeuh-megaphone

Can you help me?

**Comment by KoZeuh** [comment]
Hi, check out my last commit named fix issue#1 or download the script again ;)
